# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wg/vivado_prj/CPU/lab3/lab_3.cache/wt [current_project]
set_property parent.project_path /home/wg/vivado_prj/CPU/lab3/lab_3.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/wg/vivado_prj/CPU/lab3/lab_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/wg/vivado_prj/CPU/lab3/rtl/mipstest.coe
read_verilog -library xil_defaultlib {
  /home/wg/vivado_prj/CPU/lab3/rtl/Alu_control.v
  /home/wg/vivado_prj/CPU/lab3/rtl/Controller.v
  /home/wg/vivado_prj/CPU/lab3/rtl/adder.v
  /home/wg/vivado_prj/CPU/lab3/rtl/alu.v
  /home/wg/vivado_prj/CPU/lab3/rtl/datapath.v
  /home/wg/vivado_prj/CPU/lab3/rtl/flopr.v
  /home/wg/vivado_prj/CPU/lab3/rtl/main_decoder.v
  /home/wg/vivado_prj/CPU/lab3/rtl/mips.v
  /home/wg/vivado_prj/CPU/lab3/rtl/mux2.v
  /home/wg/vivado_prj/CPU/lab3/rtl/regfile.v
  /home/wg/vivado_prj/CPU/lab3/rtl/signext.v
  /home/wg/vivado_prj/CPU/lab3/rtl/sl2.v
  /home/wg/vivado_prj/CPU/lab3/rtl/top.v
}
read_ip -quiet /home/wg/vivado_prj/CPU/lab3/lab_3.srcs/sources_1/ip/inst_mem/inst_mem.xci
set_property used_in_implementation false [get_files -all /home/wg/vivado_prj/CPU/lab3/lab_3.srcs/sources_1/ip/inst_mem/inst_mem_ooc.xdc]

read_ip -quiet /home/wg/vivado_prj/CPU/lab3/lab_3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/wg/vivado_prj/CPU/lab3/lab_3.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
